In [1]:
import pandas as pd
import numpy as np
import pandas_datareader.data as web
import datetime as dt
from MABacktester import MABacktester as MA

In [2]:
tester = MA("BTC-USD", 50, 200, "2015-01-02", "2018-12-31")

In [3]:
tester

MABacktester(symbol = BTC-USD, MA_S = 50, MA_L = 200, start = 2015-01-02, end = 2018-12-31)

In [4]:
tester.data

Close   returns         MA_S         MA_L
Date                                                       
2015-01-02   286.769674       NaN          NaN          NaN
2015-01-05   274.473999 -0.043823          NaN          NaN
2015-01-06   286.188995  0.041796          NaN          NaN
2015-01-07   294.337006  0.028073          NaN          NaN
2015-01-08   283.348999 -0.038046          NaN          NaN
...                 ...       ...          ...          ...
2018-12-24  4078.599121  0.027012  5167.620584  6813.345667
2018-12-26  3857.297607 -0.055787  5119.089867  6786.606554
2018-12-27  3654.833496 -0.053916  5060.255736  6758.906474
2018-12-28  3870.093343  0.057228  5005.735405  6736.907893
2018-12-31  3742.700439 -0.033471  4949.700811  6714.117093

[1006 rows x 4 columns]

In [5]:
tester.test_strategy()

(30.246069, 15.529569)

In [6]:
tester.results

Close   returns         MA_S         MA_L  position  \
Date                                                                    
2015-10-16   265.050669  0.041328   239.084606   247.189806        -1   
2015-10-19   263.437012 -0.006107   238.982246   247.073143        -1   
2015-10-20   269.463013  0.022617   239.082106   247.048088        -1   
2015-10-21   266.272003 -0.011913   238.999827   246.948503        -1   
2015-10-22   274.023010  0.028694   239.152767   246.846933        -1   
...                 ...       ...          ...          ...       ...   
2018-12-24  4078.599121  0.027012  5167.620584  6813.345667        -1   
2018-12-26  3857.297607 -0.055787  5119.089867  6786.606554        -1   
2018-12-27  3654.833496 -0.053916  5060.255736  6758.906474        -1   
2018-12-28  3870.093343  0.057228  5005.735405  6736.907893        -1   
2018-12-31  3742.700439 -0.033471  4949.700811  6714.117093        -1   

            strategy   creturns  cstrategy  
Date                                        
2015-10-16       NaN   1.042194        NaN  
2015-10-19  0.006107   1.035849   1.006125  
2015-10-20 -0.022617   1.059543   0.983625  
2015-10-21  0.011913   1.046996   0.995413  
2015-10-22 -0.028694   1.077473   0.967257  
...              ...        ...        ...  
2018-12-24 -0.027012  16.037272  27.755112  
2018-12-26  0.055787  15.167102  29.347483  
2018-12-27  0.053916  14.371003  30.973224  
2018-12-28 -0.057228  15.217416  29.250451  
2018-12-31  0.033471  14.716500  30.246069  

[807 rows x 8 columns]

In [7]:
tester.plot_results()

In [8]:
tester.set_parameters(22, 100)

In [9]:
tester.test_strategy()

(56.382649, 40.598389)

In [10]:
tester.results

Close   returns         MA_S         MA_L  position  \
Date                                                                    
2015-05-27   237.283005  0.000704   235.429910   244.899497        -1   
2015-05-28   237.408005  0.000527   235.799092   244.405881        -1   
2015-05-29   233.543666 -0.016411   236.148577   243.996577        -1   
2015-06-01   222.925995 -0.046529   236.017577   243.363947        -1   
2015-06-02   225.802994  0.012823   235.547486   242.678607        -1   
...                 ...       ...          ...          ...       ...   
2018-12-24  4078.599121  0.027012  3816.353564  5883.869055        -1   
2018-12-26  3857.297607 -0.055787  3782.495731  5846.770532        -1   
2018-12-27  3654.833496 -0.053916  3763.202711  5811.533133        -1   
2018-12-28  3870.093343  0.057228  3767.337413  5780.716069        -1   
2018-12-31  3742.700439 -0.033471  3763.791071  5750.611872        -1   

            strategy   creturns  cstrategy  
Date                                        
2015-05-27       NaN   1.000704        NaN  
2015-05-28 -0.000527   1.001231   0.999473  
2015-05-29  0.016411   0.984934   1.016011  
2015-06-01  0.046529   0.940156   1.064403  
2015-06-02 -0.012823   0.952289   1.050841  
...              ...        ...        ...  
2018-12-24 -0.027012  17.200860  51.739178  
2018-12-26  0.055787  16.267555  54.707566  
2018-12-27  0.053916  15.413694  57.738161  
2018-12-28 -0.057228  16.321519  54.526686  
2018-12-31  0.033471  15.784260  56.382649  

[907 rows x 8 columns]

In [11]:
tester.plot_results()

In [12]:
tester.optimize_parameters((10, 50, 1), (100, 200, 1))

(array([ 19., 106.]), 80.308315)

In [13]:
tester.results

Close   returns         MA_S         MA_L  position  \
Date                                                                    
2015-06-04   224.324005 -0.006886   234.431509   243.960645        -1   
2015-06-05   224.483999  0.000713   233.509772   243.373044        -1   
2015-06-08   228.488998  0.017684   232.790351   242.939224        -1   
2015-06-09   229.048004  0.002444   232.155404   242.400158        -1   
2015-06-10   228.802994 -0.001070   231.756772   241.781912        -1   
...                 ...       ...          ...          ...       ...   
2018-12-24  4078.599121  0.027012  3763.115718  6002.807351        -1   
2018-12-26  3857.297607 -0.055787  3765.040857  5962.014025        -1   
2018-12-27  3654.833496 -0.053916  3733.325782  5921.478680        -1   
2018-12-28  3870.093343  0.057228  3711.812449  5880.707170        -1   
2018-12-31  3742.700439 -0.033471  3691.747237  5838.841325        -1   

            strategy   creturns  cstrategy  
Date                                        
2015-06-04       NaN   0.993138        NaN  
2015-06-05 -0.000713   0.993846   0.999287  
2015-06-08 -0.017684   1.011577   0.981772  
2015-06-09 -0.002444   1.014052   0.979376  
2015-06-10  0.001070   1.012967   0.980424  
...              ...        ...        ...  
2018-12-24 -0.027012  18.056966  73.694413  
2018-12-26  0.055787  17.077210  77.922421  
2018-12-27  0.053916  16.180851  82.239031  
2018-12-28 -0.057228  17.133860  77.664785  
2018-12-31  0.033471  16.569860  80.308315  

[901 rows x 8 columns]

In [14]:
tester.plot_results()

In [15]:
tester.plot_buys_and_sells()

__Backtesting & Forward Testing__

In [16]:
train = MA("BTC-USD", 50, 200, "2015-01-01", "2018-12-31")

In [17]:
train.optimize_parameters((10, 50, 1), (100, 200, 1)) 

(array([ 19., 106.]), 80.308315)

In [18]:
train.plot_results()

In [19]:
tester = MA("BTC-USD", 19, 106, "2019-01-01", dt.date.today())

In [20]:
tester.test_strategy() # forward testing ("out-sample")

(1.08737, -3.924541)

In [21]:
tester.plot_results()

#### Testing with optimized parameters for the whole time period

In [22]:
tester = MA("BTC-USD", 19, 106, "2015-01-01", dt.date.today())

In [23]:
tester.test_strategy()

(103.950756, -78.198386)

In [24]:
tester.plot_results()

In [25]:
tester.optimize_parameters((10, 50, 1), (100, 200, 1))

(array([ 26., 112.]), 123.351932)

In [26]:
opti_btc = MA("BTC-USD", 26, 112, "2015-01-01", dt.date.today())

In [27]:
opti_btc.test_strategy()

(123.351932, -55.759335)

In [28]:
opti_btc.results

Close   returns          MA_S          MA_L  position  \
Date                                                                       
2015-06-12    231.975662  0.009837    233.232205    243.145831        -1   
2015-06-15    236.822998  0.020681    233.212551    242.699878        -1   
2015-06-16    250.895004  0.057722    233.554782    242.489352        -1   
2015-06-17    249.283997 -0.006442    233.828859    242.159843        -1   
2015-06-18    249.007004 -0.001112    234.132513    241.755111        -1   
...                  ...       ...           ...           ...       ...   
2022-04-05  45555.992188 -0.023145  42707.272286  47451.579125        -1   
2022-04-06  43206.738281 -0.052946  42663.122346  47298.391137        -1   
2022-04-07  43503.847656  0.006853  42646.958133  47164.654181        -1   
2022-04-08  42425.824219 -0.025092  42645.959485  47002.187105        -1   
2022-04-11  41142.753906 -0.030709  42728.909305  46817.640997        -1   

            strategy    creturns   cstrategy  
Date                                          
2015-06-12       NaN    1.009885         NaN  
2015-06-15 -0.020681    1.030988    0.979532  
2015-06-16 -0.057722    1.092249    0.924593  
2015-06-17  0.006442    1.085235    0.930568  
2015-06-18  0.001112    1.084030    0.931603  
...              ...         ...         ...  
2022-04-05  0.023145  198.323902  111.402209  
2022-04-06  0.052946  188.096637  117.459414  
2022-04-07 -0.006853  189.390076  116.657226  
2022-04-08  0.025092  184.696998  119.621440  
2022-04-11  0.030709  179.111267  123.351932  

[1721 rows x 8 columns]

In [29]:
opti_btc.plot_results()

In [30]:
opti_btc.plot_buys_and_sells()